name: build + test
on: [push]  # all push to any branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running in response to ${{ github.event_name }}"

      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install tox
        run: |
          pip install -q tox
      
      - name: Test
        run: make test
