name: build + test
on: [push] # all push to any branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running in response to ${{ github.event_name }}"

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: ansible/collections/ansible_collections/aerospike/acl

      - uses: actions/setup-python@v3
        with:
          python-version: "3.6"

      - name: Setup virtualenv and run the unit tests
        working-directory: ansible/collections/ansible_collections/aerospike/acl
        run: |
          make format
          make test
