name: publish release
on: [workflow_dispatch]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          path: ansible/collections/ansible_collections/aerospike/acl

      - name: Print the describe-version
        run: |
          echo "::notice::output of describe-version for this branch: $(tools/describe-version)"

      - name: Check release conditions
        id: check_release_conditions
        run: |
          release_version="$(tools/describe-version)"
          if [[ ! "$release_version" =~ ^[0-9]+(\.[0-9]+)*(\.post[0-9]+)?$ ]]; then
            echo "::error::This is not a release. To create a release, tag a commit with a release version, e.g.: git tag -a -m v1.2.3 v1.2.3; git push --tags"
            false
          fi
          echo "::notice::Release version: $release_version"
          echo "::set-output name=release_version::$release_version"

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.6"

      - name: Package release
        id: package_release
        working-directory: ansible/collections/ansible_collections/aerospike/acl
        run: |
          make build
          echo "::set-output name=release_artifacts::$(make print-release-artifact)"

      - name: Create GitHub release with gh
        run: |
          link=$(tools/release \
            "${{ steps.check_release_conditions.outputs.release_version }}" \
            "${{ secrets.GITHUB_TOKEN }}" \
            ${{ steps.package_release.outputs.release_artifacts }}
            )
          echo "::notice::Release link: $link"
